### ISSUE TITLE
Parsing N Tokens

### ISSUE THREAD

**Issue by rbrenton** [GameSurge/srvx#4]
From http://ircd.bircd.org/bewarep10.txt

{83} many P10 services, including srvx, break on parsing N tokens with umode +h (sethost) because they don't parse the numeric and base64 IP counting from the end.

**Comment by entrope** [comment]
Strictly speaking, P10 doesn't have such a thing as +h user mode, so there's no reason to count backwards for  those other fields.  However, srvx *has* counted backwards since we migrated the code from arch in early 2004 (which was srvx 1.3).
